
2022-06-03 22:31:07.660994 spotify.py - getNewAccessToken --> <class 'TypeError'> - ("abspath() missing 1 required positional argument: 'path'",) - abspath() missing 1 required positional argument: 'path'
2022-06-03 22:31:07.661994 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\spotify.py", line 34, in getNewAccessToken
    folder_name = os.path.abspath()
TypeError: abspath() missing 1 required positional argument: 'path'

2022-06-03 22:31:23.707337 spotify.py - getNewAccessToken --> <class 'TypeError'> - ("abspath() missing 1 required positional argument: 'path'",) - abspath() missing 1 required positional argument: 'path'
2022-06-03 22:31:23.707337 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\spotify.py", line 35, in getNewAccessToken
    folder_name = os.path.abspath()
TypeError: abspath() missing 1 required positional argument: 'path'

2022-06-03 22:34:03.101738 spotify.py - getNewAccessToken --> <class 'OSError'> - (22, 'Invalid argument') - [Errno 22] Invalid argument: 'e:\\docs\\phyton projects\\SpotifyWebAppV2.0\\spotr\\static\refresh_token.txt'
2022-06-03 22:34:03.103741 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\spotify.py", line 34, in getNewAccessToken
    fileOpen = open(ROOT_DIR + "\static\refresh_token.txt", "r")
OSError: [Errno 22] Invalid argument: 'e:\\docs\\phyton projects\\SpotifyWebAppV2.0\\spotr\\static\refresh_token.txt'

2022-06-04 22:11:51.232890 err - spotify.py - getNewAccessToken1 --> <class 'FileNotFoundError'> - (2, 'No such file or directory') - [Errno 2] No such file or directory: 'e:\\docs\\phyton projects\\SpotifyWebAppV2.0\\spotr/static/refresh_token.txt'
2022-06-04 22:11:51.233890 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\spotify.py", line 36, in getNewAccessToken
    fileOpen = open(ROOT_DIR + "/static/refresh_token.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'e:\\docs\\phyton projects\\SpotifyWebAppV2.0\\spotr/static/refresh_token.txt'

2022-06-04 22:25:21.972451 err - spotify.py - getNewAccessToken1 --> <class 'FileNotFoundError'> - (2, 'No such file or directory') - [Errno 2] No such file or directory: 'e:\\docs\\phyton projects\\SpotifyWebAppV2.0\\spotr/static/refresh_token.txt'
2022-06-04 22:25:21.972451 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\spotify.py", line 37, in getNewAccessToken
    fileOpen = open(ROOT_DIR + "/static/refresh_token.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'e:\\docs\\phyton projects\\SpotifyWebAppV2.0\\spotr/static/refresh_token.txt'

2022-06-06 21:15:29.196671 msg - common.py - getTrackInfo --> requesting track info for trackID: 3OWAyHmNMACLPQNPEFEZNY
2022-06-06 21:15:29.211671 err - spotify.py - getNewAccessToken2 --> <class 'NameError'> - ("name 'requests' is not defined",) - name 'requests' is not defined
2022-06-06 21:15:29.211671 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\common.py", line 161, in getNewAccessToken
    response = requests.post(url, data=body_params, auth=(spotify_client_id, spotify_client_secret), verify=False)
NameError: name 'requests' is not defined

2022-06-06 21:15:29.212670 err - spotify.py - apiReqSpotify --> error getNewAccessToken()
2022-06-06 21:17:14.031371 msg - common.py - getTrackInfo --> requesting track info for trackID: 3OWAyHmNMACLPQNPEFEZNY
2022-06-06 21:18:01.035427 msg - common.py - getTrackInfo --> requesting track info for trackID: 3OWAyHmNMACLPQNPEFEZNY
2022-06-06 21:38:10.655726 msg - common.py - getTracksFromLikedList --> requesting tracks from liked list.
2022-06-06 21:40:51.203281 msg - common.py - getTracksFromLikedList --> requesting tracks from liked list.
2022-06-06 21:43:05.953544 msg - common.py - getTracksFromLikedList --> requesting tracks from liked list.
2022-06-06 21:43:39.288586 msg - common.py - getTracksFromLikedList --> requesting tracks from liked list.
2022-06-06 23:01:20.375255 msg - common.py - getTracksFromArtist --> requesting albums from artist 0V7j0A3N5hup0XNQVKYvrQ.
2022-06-07 21:23:22.834172 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 21:23:23.539168 err - common.py - getTracksFromPlaylist6 --> <class 'KeyError'> - ('id',) - 'id'
2022-06-07 21:23:23.540167 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\common.py", line 420, in getTracksFromPlaylist
    if track["id"]: #check if valid item
KeyError: 'id'

2022-06-07 21:29:22.333734 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 21:29:22.958569 err - common.py - getTracksFromPlaylist6 --> <class 'KeyError'> - ('id',) - 'id'
2022-06-07 21:29:22.959570 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\common.py", line 420, in getTracksFromPlaylist
    if track["id"]: #check if valid item
KeyError: 'id'

2022-06-07 21:32:54.706372 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 21:35:33.304294 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 21:40:44.216260 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 21:41:35.888413 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 21:43:06.053467 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 21:48:18.688375 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 21:49:58.035954 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 21:52:46.415671 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 6okeRq2A2cNvZEOUnrqIXW.
2022-06-07 23:08:37.740882 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 6okeRq2A2cNvZEOUnrqIXW.
2022-06-07 23:08:38.732959 err - common.py - getTracksFromPlaylist6 --> <class 'TypeError'> - ("'NoneType' object is not subscriptable",) - 'NoneType' object is not subscriptable
2022-06-07 23:08:38.734963 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\common.py", line 426, in getTracksFromPlaylist
    if track["track"]["id"]: #check if valid item
TypeError: 'NoneType' object is not subscriptable

2022-06-07 23:09:39.576050 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 23:09:40.665913 err - common.py - getTracksFromPlaylist6 --> <class 'TypeError'> - ('must be real number, not str',) - must be real number, not str
2022-06-07 23:09:40.666914 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\common.py", line 441, in getTracksFromPlaylist
    log("err - common.py - getTracksFromPlaylist3 --> invalid track[\"ID\"] in playlist " + playlistID + ".")
TypeError: must be real number, not str

2022-06-07 23:12:03.545419 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 23:12:04.603087 err - common.py - getTracksFromPlaylist6 --> <class 'TypeError'> - ('must be real number, not str',) - must be real number, not str
2022-06-07 23:12:04.604086 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\common.py", line 441, in getTracksFromPlaylist
    log("err - common.py - getTracksFromPlaylist3 --> invalid track[ID] in playlist " + playlistID + ".")
TypeError: must be real number, not str

2022-06-07 23:12:48.393636 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 23:12:49.406855 err - common.py - getTracksFromPlaylist6 --> <class 'TypeError'> - ('must be real number, not str',) - must be real number, not str
2022-06-07 23:12:49.406855 TRACEBACK --> Traceback (most recent call last):
  File "e:\docs\phyton projects\SpotifyWebAppV2.0\spotr\common.py", line 441, in getTracksFromPlaylist
    log("err - common.py - getTracksFromPlaylist3 --> invalid trackID in playlist " + playlistID + ".")
TypeError: must be real number, not str

2022-06-07 23:13:27.758386 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 23:13:28.858187 err - common.py - getTracksFromPlaylist3 --> invalid trackID in playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 23:21:23.456083 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 23:21:24.621390 err - common.py - getTracksFromPlaylist3 --> invalid trackID in playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 23:22:27.155494 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 23:22:28.250626 err - common.py - getTracksFromPlaylist3 --> invalid trackID in playlist 63o9W2iYSC7BHHn38CuRD1.
2022-06-07 23:23:07.873553 msg - common.py - getTracksFromPlaylist --> requesting tracks from playlist 0HGCkTEihw72V8Eltpzpig.